services:
  geoanalytics_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geoanalytics_backend
    restart: always
    ports:
      - "8001:8000"  # 8001 sur ton host â†’ 8000 dans le container
    env_file:
      - .env
    volumes:
      # Monte uniquement le dossier app pour live reload
      - ./backend/app:/app/app
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - geo_network
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload   

  db:
    image: postgis/postgis:15-3.4
    container_name: geoanalytics_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - geo_network
    volumes:
      - geoanalytics_db_data:/var/lib/postgresql/data

  eviction:
    build:
      context: ./eviction
      dockerfile: Dockerfile.eviction
    container_name: geoanalytics_eviction
    restart: no
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - geo_network
    command: ["python", "main.py"] # ou le script principal d'eviction

  geoanalytics_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: geo-frontend
    restart: always
    ports:
      - "8501:8501"          
    env_file:
      - .env
    depends_on:
      - geoanalytics_backend
    networks:
      - geo_network
    # volumes:
    #   - ./frontend:/app
    command: [
      "streamlit",
      "run",
      "app.py",
      "--server.port=8501",
      "--server.address=0.0.0.0"
    ]

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - geo_network
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - geo_network
    command:
      - --config.file=/etc/prometheus/prometheus.yml

networks:
  geo_network:
    driver: bridge

volumes:
  geoanalytics_db_data: {}
