global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['geoanalytics_backend:8001']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
